# Generated by Django 4.2.3 on 2023-07-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
