# Generated by Django 4.2.3 on 2023-07-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('user', '0003_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronmodel',
            name='station_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.stationmodel'),
        ),
    ]
