# Generated by Django 4.2.3 on 2023-07-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(max_length=200, upload_to='images/')),
                ('hourprice', models.PositiveSmallIntegerField(default='')),
                ('phone_number', models.CharField(default='', max_length=122)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('adress', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='BronedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.bronmodel')),
            ],
            options={
                'db_table': 'broned',
            },
        ),
    ]
